[package]
name = "rust-chess-gl"
version = "0.1.0"
authors = ["Alexandre Janin <alexandrejanin92@gmail.com>"]

[build-dependencies]
walkdir = "*"

[dependencies]
gl = "*"
cgmath = "*"
image = "*"
ron = "*"
serde = "*"
sdl2 = "*"

