[package]
name = "rust-chess-gl"
version = "0.1.0"
authors = ["Alexandre Janin <alexandrejanin92@gmail.com>"]

[dependencies]
gl = "*"
ron = "*"
serde = "*"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["image", "ttf"]

