[package]
name = "rust-chess-gl"
version = "0.1.0"
authors = ["Alexandre Janin <alexandrejanin92@gmail.com>"]

[build-dependencies]
fs_extra = "*"

[dependencies]
floating-duration = "*"
rand = "*"

sdl2 = "*"
gl = "*"
cgmath = "*"

image = "*"
ron = "*"
serde = "*"

